---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# fantasypros

<!-- badges: start -->
<!-- badges: end -->

The goal of fantasypros is to ...

## Installation

You can install the released version of fantasypros from [CRAN](https://CRAN.R-project.org) with:

``` r
# not on CRAN
install.packages("fantasypros")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("jpiburn/fantasypros")
```
## Example

This is a basic example which shows you how to solve a common problem:

## Weekly Snap Counts
```{r snap-counts, message=FALSE}
library(fantasypros)

fp_snap_counts(season = 2018)

fp_snap_counts(pos = "defense", season = 2018, percentage = TRUE)

```


## Detailed Snap Analysis
```{r snap-analysis, message=FALSE}
library(fantasypros)

# all offensive positions for weeks 5-9 of the 2018 season
fp_snap_analysis(season = 2018, start_week = 5, end_week = 9)
```

## Weekly Targets
```{r targets, message=FALSE}
library(fantasypros)

# total targets for TE's in the 2014 season
fp_targets(pos = "TE", season = 2014)
```
